curriculum/models/skill.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from curriculum.models import utils

SKILL_LEVELS = (
    (None, _('unknown')),
    ('B', _('beginner')),
    ('S', _('skilled')),
    ('A', _('advanced')),
    ('E', _('expert')),
)


@python_2_unicode_compatible
class Skill(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name=_("name"))
    description = models.TextField(max_length=2000, blank=True, verbose_name=_("description"))
    url = models.URLField(max_length=300, blank=True, verbose_name=_("URL"))
    tags = models.CharField(max_length=500, blank=True, verbose_name=_("tags"))
    color = models.CharField(max_length=50, blank=True, verbose_name=_("color"))

    class Meta:
        app_label = 'curriculum'
        ordering = ('name',)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class SkillItem(models.Model):
    resume = models.ForeignKey("curriculum.Resume", related_name='skills')

    skill = models.ForeignKey('curriculum.Skill', related_name='items')
    level = models.CharField(max_length=1, choices=SKILL_LEVELS, verbose_name=_("level"))
    category = models.CharField(max_length=50, blank=True, verbose_name=_("category"))

    start_year = models.IntegerField(choices=utils.YEARS, default=utils.current_year, null=True, blank=True, verbose_name=_("start year"))
    start_month = models.IntegerField(choices=utils.MONTHS, default=utils.current_month, null=True, blank=True, verbose_name=_("start month"))

    weight = models.IntegerField(choices=utils.WEIGHTS, default=1, verbose_name=_("weight"))

    class Meta:
        app_label = 'curriculum'
        unique_together = ('skill', 'resume')

    def __str__(self):
        return self.skill.name

curriculum/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.admin import widgets
from django.contrib.staticfiles.templatetags.staticfiles import static
from curriculum import models


class ResumeExportForm(forms.Form):
    hide_image = forms.BooleanField()
    hide_resume = forms.BooleanField()

    hide_phone = forms.BooleanField()
    hide_city = forms.BooleanField()
    hide_country = forms.BooleanField()
    hide_address = forms.BooleanField()

    hide_email = forms.BooleanField()
    hide_website = forms.BooleanField()
    hide_skype = forms.BooleanField()
    hide_twitter = forms.BooleanField()
    hide_linkedin = forms.BooleanField()
    hide_stackoverflow = forms.BooleanField()
    hide_github = forms.BooleanField()
    hide_experience_description = forms.BooleanField()
    hide_experience_environment = forms.BooleanField()
    hide_certification_description = forms.BooleanField()
    hide_training_description = forms.BooleanField()
    hide_project_contribution = forms.BooleanField()
    hide_project_url = forms.BooleanField()

    class Media:
        css = {'all': (static('admin/css/widgets.css'),), }

    def __init__(self, instance, *args, **kwargs):
        super(ResumeExportForm, self).__init__(*args, **kwargs)
        self.instance = instance
        self.fields['experiences'] = forms.ModelMultipleChoiceField(
            queryset=instance.experiences.all(),
            initial=instance.experiences.all(),
            widget=widgets.FilteredSelectMultiple(_("experiences"), is_stacked=False,
                    attrs={'size': 5, 'style': 'height: unset'}))
        self.fields['projects'] = forms.ModelMultipleChoiceField(
            queryset=instance.projects.all(),
            initial=instance.projects.all(),
            widget=widgets.FilteredSelectMultiple(_("projects"), is_stacked=False,
                    attrs={'size': 5, 'style': 'height: unset'}))
        self.fields['skills'] = forms.ModelMultipleChoiceField(
            queryset=instance.skills.order_by('skill__name'),
            initial=instance.skills.all(),
            widget=widgets.FilteredSelectMultiple(_("skills"), is_stacked=False,
                    attrs={'size': 5, 'style': 'height: unset'}))
        self.fields['certifications'] = forms.ModelMultipleChoiceField(
            queryset=instance.certifications.all(),
            initial=instance.certifications.all(),
            widget=widgets.FilteredSelectMultiple(_("certifications"), is_stacked=False,
                    attrs={'size': 5, 'style': 'height: unset'}))
        self.fields['trainings'] = forms.ModelMultipleChoiceField(
            queryset=instance.trainings.all(),
            initial=instance.trainings.all(),
            widget=widgets.FilteredSelectMultiple(_("trainings"), is_stacked=False,
                    attrs={'size': 3, 'style': 'height: unset'}))
        self.fields['languages'] = forms.ModelMultipleChoiceField(
            queryset=instance.languages.all(),
            initial=instance.languages.all(),
            widget=widgets.FilteredSelectMultiple(_("languages"), is_stacked=False,
                    attrs={'size': 4, 'style': 'height: unset'}))


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = models.Experience
        exclude = ()

    def clean(self):
        cleaned_data = super(ExperienceForm, self).clean()
        if cleaned_data.get('end_month') and not cleaned_data.get('end_year'):
            raise forms.ValidationError(_(
                "You must specify an end year with end month."))
        if cleaned_data.get('end_year'):
            if cleaned_data.get('end_year') < cleaned_data.get('start_year'):
                raise forms.ValidationError(_("End year is lower than start."))
        if cleaned_data.get('end_year') == cleaned_data.get('start_year'):
            if cleaned_data.get('end_month') < cleaned_data.get('start_month'):
                raise forms.ValidationError(_("End month is lower than start."))

    def clean_end_year(self):
        data = self.cleaned_data['end_year']
        if not self.cleaned_data['still'] and not data:
            raise forms.ValidationError(_(
                "You must specify an end year if experience is finished."))
        return data

curriculum/templates/curriculum/base_page.html
{% block style %}
{% endblock %}

{% block page_header %}
{% endblock %}

{% block content %}
<div id="bodyContent">
</div>
{% endblock %}

{% block page_foot %}
<div id="footerContent">
  <pdf:pagenumber>
</div>
{% endblock %}
<pdf:nextpage>

curriculum/templates/curriculum/base_pdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
 <head>
  <title>
  {% block title %}{% endblock %}
  </title>
  
  <style type="text/css">
   {% block style %}
   {% endblock %}
  </style>
 </head>
 
 <body>
  {% for page in pages %}
    {{ page }}
  {% endfor %}
 </body>
</html>

curriculum/templates/curriculum/classic.html
{% load i18n curriculum %}

<html>
 <head>
  <style type="text/css">
  @page {
    size: {{ pagesize }};
    margin: 1cm;
    border: 0pt solid white;
  }
  * {
    font-size: 14px;
    line-height: 15px;
  }
  .center {
    text-align: center;
  }
  a[href], .h1, .h2 {
    color: #0066B2;
  }
  .h1 {
    font-size: 25px;
  }
  .h2 {
    font-size: 20px;
  }
  .h3 {
    font-size: 16px;
    color: #3066B2;
  }
  .h3 small {
    color: #DDDDDD;
  }
  .separator {
    border: 3px;
    line-height: 0px;
  }
  </style>
 </head>
 <body>
  <div id="content_frame">
   <table>
    <tr>
     <td style="width: 330px">
      {% if resume.image %}
       <img height="120" width="120" src="{{ resume.image.url }}"/>
      {% endif %}
     </td>
     <td class="center">
      <h1 class="h1">{{ resume.firstname }} {{ resume.lastname }}<br>{{ resume.title }}</h1>
      {% if resume.resume %}<i>{{ resume.resume }}</i>{% endif %}
     </td>
     <td style="width: 330px; text-align: right">
        {% if resume.phone %}{{ resume.phone }}<br>{% endif %}
        {% if resume.city or resume.country %}{{ resume.city|default:"" }} {{ resume.country|default:"" }}<br>{% endif %}
        {% if resume.address %}{{ resume.address }}<br>{% endif %}
        {% if resume.email %}<a href="mailto:{{ resume.email }}">{{ resume.email }}</a><br>{% endif %}
        {% if resume.website %}{{ resume.website|shortlink|safe }}<br>{% endif %}
        {% if resume.skype %}<b>Skype</b>: {{ resume.skype }}<br>{% endif %}
        {% if resume.twitter %}<b>Twitter</b>: {{ resume.twitter }}<br>{% endif %}
        {% if resume.stackoverflow %}<b>stackoverflow</b>: <a href="http://stackoverflow.com/users/{{ resume.stackoverflow }}">{{ resume.stackoverflow }}</a><br>{% endif %}
        {% if resume.github %}<b>GitHub</b>: <a href="https://github.com/{{ resume.github }}">{{ resume.github }}</a><br>{% endif %}
     </td>
    </tr>
   </table>
   {% if skills %}
    <hr class=separator>
    <h2 class="center h2">{% trans "Skills" %}</h2>
    {% for skill in skills %}
     {% ifchanged skill.category %}
      <h3 class="h3">{{ skill.category|capfirst }}</h3>
     {% endifchanged %}
      {{ skill }},
    {% endfor %}
   {% endif %}
   
   {% if projects %}
    <hr class=separator>
    <h2 class="center h2">{% trans "Projects" %}</h2>
    {% for project in projects %}
     <table>
      <tr>
       <td>
        <h3 class="h3">{{ project.project.title }} <small>{% daterange_display project.start_year project.start_month project.end_year project.end_month %}</small></h3>
       </td>
       <td style="text-align: right">
        {% if not hide_project_url and project.project.url %}<small><a href="{{ project.project.url }}">{{ project.project.url }}</a></small>{% endif %}
       </td>
      </tr>
     </table>
     {% if not hide_project_contribution and project.contribution %}
      {{ project.contribution|linebreaksbr }}
      <br>
     {% endif %}
     <br>
    {% endfor %}
   {% endif %}
   
   {% if experiences %}
    <hr class=separator>
    <h2 class="center h2">{% trans "Experiences" %}</h2>
    {% for experience in experiences %}
     <h3 class="h3">{{ experience }} <small>{% daterange_display experience.start_year experience.start_month experience.end_year experience.end_month %}</small></h3>
     {% if not hide_experience_description and experience.description %}{{ experience.description|linebreaksbr }}{% endif %}
     {% if not hide_experience_environment and experience.environment %}<br><br><b>{% trans "Technical environment" %}</b>: {{ experience.environment }}<br>{% endif %}
    {% endfor %}
   {% endif %}
   
   {% if trainings %}
    <hr class=separator>
    <h2 class="center h2">{% trans "Training" %}</h2>
    {% for training in trainings %}
     <h3 class="h3">{{ training.degree }} in {{ training.topic }} <small>{% daterange_display training.year training.month %}</small></h3>
     {% if not hide_training_description and training.description %}{{ training.description|linebreaksbr }}{% endif %}
    {% endfor %}
   {% endif %}
   
   {% if certifications %}
    <hr class=separator>
    <h2 class="center h2">{% trans "Certifications" %}</h2>
    {% for certification in certifications %}
     <h3 class="h3">{{ certification }} <small>{% daterange_display certification.start_year certification.start_month %}</small></h3>
     {% if not hide_certification_description and certification.certification.description %}{{ certification.certification.description|linebreaksbr }}{% endif %}
    {% endfor %}
   {% endif %}
   
   {% if resume.hobbies %}
    <hr class=separator>
    <h2 class="center h2">{% trans "Hobbies" %}</h2>
    {{ resume.hobbies|linebreaksbr }}
   {% endif %}
  </div>  
 </body>
</html>

curriculum/templates/curriculum/export.html
{% extends "admin/change_form.html" %}
{% load i18n l10n static admin_urls %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% static "admin/js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} delete-confirmation delete-selected-confirmation{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block content %}
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/SelectBox.js"></script>
<script type="text/javascript" src="/static/admin/js/SelectFilter2.js"></script>
<div id="content" class="colM">
 {% for form in formset %}
  <h2>{{ form.instance }}</h2>
  <div id="content-main">
   <form method="POST" action="" target="_blank">
    {% csrf_token %}
    <input type="hidden" name="action" value="export_resume">
    <input type="hidden" name="_selected_action" value="{{ form.instance.id }}">
    <fieldset class="module aligned ">
     <div class="form-row">
      <div class="field-box">
       <label>{{ form.hide_image.label }}:</label>
       {{ form.hide_image }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_resume.label }}:</label>
       {{ form.hide_resume }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label>{{ form.hide_phone.label }}:</label>
       {{ form.hide_phone }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_city.label }}:</label>
       {{ form.hide_city }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_country.label }}:</label>
       {{ form.hide_country }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_address.label }}:</label>
       {{ form.hide_address }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label>{{ form.hide_email.label }}:</label>
       {{ form.hide_email }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_website.label }}:</label>
       {{ form.hide_website }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_skype.label }}:</label>
       {{ form.hide_skype }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_twitter.label }}:</label>
       {{ form.hide_twitter }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_stackoverflow.label }}:</label>
       {{ form.hide_stackoverflow }}
      </div>
      <div class="field-box">
       <label>{{ form.hide_github.label }}:</label>
       {{ form.hide_github }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label for="id_experiences">{{ form.experiences.label }}:</label>
       {{ form.experiences }}
      </div>
      <div class="field-box">
       <label for="id_hide_experience_description">{{ form.hide_experience_description.label }}:</label>
       {{ form.hide_experience_description }}
      </div>
      <div class="field-box">
       <label for="id_hide_experience_environment">{{ form.hide_experience_environment.label }}:</label>
       {{ form.hide_experience_environment }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label for="id_projects">{{ form.projects.label }}:</label>
       {{ form.projects }}
      </div>
      <div class="field-box">
       <label for="id_hide_project_contribution">{{ form.hide_project_contribution.label }}:</label>
       {{ form.hide_project_contribution }}
      </div>
      <div class="field-box">
       <label for="id_hide_project_url">{{ form.hide_project_url.label }}:</label>
       {{ form.hide_project_url }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label for="id_skills">{{ form.skills.label }}:</label>
       {{ form.skills }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label for="id_trainings">{{ form.trainings.label }}:</label>
       {{ form.trainings }}
      </div>
      <div class="field-box">
       <label for="id_hide_training_description">{{ form.hide_training_description.label }}:</label>
       {{ form.hide_training_description }}
      </div>
     </div>
     <div class="form-row">
      <div class="field-box">
       <label for="id_certifications">{{ form.certifications.label }}:</label>
       {{ form.certifications }}
      </div>
      <div class="field-box">
       <label for="id_hide_certification_description">{{ form.hide_certification_description.label }}:</label>
       {{ form.hide_certification_description }}
      </div>
     </div>
     <div class="form-row">
      <label for="id_languages">{{ form.languages.label }}:</label>
       {{ form.languages }}
     </div>
    </fieldset>
    <div class="submit-row">
     <input type="submit" value="{% trans "Export" %}" class="default" name="_export">
    </div>
   <form>
  </div>
 {% endfor %}
</div>
{% endblock %}

curriculum/templates/curriculum/single_page.html
{% load i18n curriculum %}

<style type="text/css">
@page {
  size: {{ pagesize }};
  margin: 0px;
}
* {
  font-size: 15px;
  height: 0px;
  padding: 2px;
  margin: 0px;
  line-height: 15px;
  text-indent: 0px;
  list-style-type: none;
}
table {
  -pdf-keep-in-frame-mode: shrink;
}
#top {
  padding: 10px;
  text-align: center;
}
#top #title {
  font-size: 30px;
}
#side-bar {
  padding: 10px;
  vertical-align: top;
  width: 400px;
}
#side-bar ul {
  margin-left: 10px;
}
#images-bar {
  text-align: center;
}
#content-bar {
  padding: 10px;
  padding-left: 30px;
  vertical-align: top;
}
#content-bar .h1 {
  font-size: 21px;
  text-decoration: underline;
  text-align: center;
}
#content-bar .h2 {
  font-size: 19px;
}
#footer {
  line-height: 0px;
}
.blue-background {
  background-color: #002e40;
  color: #FFFFFF;
}
.light-blue-background {
  background-color: #0C516C;
  color: #FFFFFF;
}
.blue-background a, .light-blue-background a {
  color: #FFF;
}
.grey-background {
  background-color: #DBDBDB;
  color: #444;
}
.grey-background a {
  color: #444;
  font-size: 19px;
}
.padding td {
  text-align: right;
  vertical-align: bottom;
  line-height: 50px;
}
</style>

<div class="bodyContent">
 <table style="width:100%">
  <tr>
   <td id="top" class="blue-background" colspan="2">
    <b id="title">{{ resume.firstname }} {{ resume.lastname }} - {{ resume.title }}</b>
    <br><br>
    <i>{{ resume.resume }}</i>
   </td>
  </tr>

  <tr>
   <td id="side-bar" class="light-blue-background">
    <p id="images-bar">
    {% if resume.image %}
    <img height="100" width="100" src="{{ resume.image.url }}"/>
    {% endif %}
    <img height="100" width="100" src="{{ resume.website_qrcode }}"/>
    <p>
    <b>{% trans "Contact" %}</b>
    <ul>
     <li><b>{% trans "Phone" %}:</b> {{ resume.phone }}</li>
     <li><b>{% trans "Email" %}:</b> <a href="mailto:{{ resume.email }}">{{ resume.email }}</a></li>
     <li><b>{% trans "Website" %}:</b> {{ resume.website|shortlink|safe }}</li>
    </ul>
    <b>{% trans "Skills" %}</b>
    <ul>
     {% for skill in skills %}
     <li>{{ skill }} - {{ skill.get_level_display|capfirst }}</li>
     {% endfor %}
    </ul>
    <b>{% trans "Languages" %}</b>
    <ul>
     {% for language in resume.languages.all %}
     <li>{{ language }} - {{ language.get_level_display|capfirst }}</li>
     {% endfor %}
    </ul>
    <b>{% trans "Driving license" %}:</b><br>{{ resume.driving_license }}
    <br><br>
    <b>{% trans "Hobbies" %}:</b><br>{{ resume.hobbies }}
   </td>

   <td id="content-bar" class="grey-background">
    <b class="h1">{% trans "Projects" %}</b>
    <div>
     {% for project in projects %}
      <b class="h2">{{ project.project.url|shortlink:project|safe }}</b>
      <small>{% daterange_display project.start_year project.start_month project.end_year project.end_month %}</small>
      <br>
      {{ project.contribution|linebreaksbr }}
      <br><br>
     {% endfor %}
    </div>

    <b class="h1">{% trans "Experiences" %}</b>
    <div>
     {% for experience in experiences %}
      <b class="h2">{{ experience }}</b>
      <small>{% daterange_display experience.start_year experience.start_month experience.end_year experience.end_month %}</small>
      <br>
      {{ experience.description|linebreaksbr }}
      <br><br>
     {% endfor %}
    </div>

    <b class="h1">{% trans "Trainings" %}</b>
    <div>
     {% for training in trainings %}
     <b class="h3">{{ training.degree }} in {{ training.topic }}</b>
      <small>{% daterange_display training.year training.month %}</small>
      <br><br>
     {% endfor %}
    </div>

    <b class="h1">{% trans "Certifications" %}</b>
    <div>
     {% for certification in certifications %}
      <b class="h3">{{ certification }}</b>
      <small>{% daterange_display certification.start_year certification.start_month %}</small>
     {% endfor %}
    </div>
    <br>
   </td>
  </tr>

 </table>
</div>